create database DeptManagement
on primary 
( 
  size = 100,
  filegrowth = 10,
  maxsize = 2GB,
  filename = 'D:\MiniProject\DeptManagement.mdf',
  name = DeptManagement
)
log on 
(
  size = 200,
  filegrowth = 20,
  maxsize = Unlimited,
  filename = 'D:\MiniProject\DeptManagement.ldf',
  name = DeptManagement_log
);

use DeptManagement


CREATE TABLE EMPLOYEE
(
	EmpId INT IDENTITY(1,1) NOT NULL,
    EmpName NVARCHAR(50) NOT NULL,
    DateOfBirth DATE,
    Sex NVARCHAR(3),
	Address NTEXT,
	Phone CHAR(10)	
);


CREATE TABLE DEPARTMENT
(
	DeptID INT IDENTITY(1,1) NOT NULL,
    DeptName NVARCHAR(50) NOT NULL,
   	DeptManagerID INT NOT NULL
);


CREATE TABLE SALARY
(
	EmpId INT NOT NULL,
	Salary DECIMAL (15,2),
	DayOff INT,
    Allowance DECIMAL (15,2)
);


CREATE TABLE WORK_ON
(
	EmpId INT NOT NULL,
	DeptId INT NOT NULL,
	Position NVARCHAR (15)
)

CREATE TABLE ACCOUNT
(
	UserName VARCHAR (20) NOT NULL, 
	Pass VARCHAR (50)
)


ALTER TABLE EMPLOYEE
ADD CONSTRAINT PK_EmpId PRIMARY KEY (EmpId);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT PK_DeptID PRIMARY KEY (DeptID);

ALTER TABLE SALARY
ADD CONSTRAINT PK_Salary PRIMARY KEY (EmpId);

ALTER TABLE WORK_ON
ADD CONSTRAINT PK_WorkOn PRIMARY KEY (EmpId,DeptID);

ALTER TABLE ACCOUNT
ADD CONSTRAINT PK_Account PRIMARY KEY (UserName);

ALTER TABLE SALARY
ADD CONSTRAINT FK_Salary FOREIGN KEY (EmpId)  REFERENCES EMPLOYEE (EmpId);

ALTER TABLE WORK_ON
ADD CONSTRAINT FK_EmpId FOREIGN KEY (EmpId)  REFERENCES EMPLOYEE (EmpId);

ALTER TABLE WORK_ON
ADD CONSTRAINT FK_DepId FOREIGN KEY (DeptID)  REFERENCES DEPARTMENT (DeptID);

select * from EMPLOYEE

INSERT INTO EMPLOYEE
VALUES('Huỳnh Thị Phước Minh','10/13/1997','Nữ','Hồ Chí Minh','0932571394')

INSERT INTO EMPLOYEE
VALUES('Nguyễn Văn An','06/20/1990','Nam','Hồ Chí Minh','0912078364')

INSERT INTO EMPLOYEE
VALUES('Trần Thị Quỳnh Hương','02/18/1987','Nữ','Hồ Chí Minh','0967259103')

INSERT INTO EMPLOYEE
VALUES('Trương Tuấn Hưng','10/22/1993','Nam','Vũng Tàu','0912078530')

INSERT INTO EMPLOYEE
VALUES('Lưu Thanh Nhàn','07/08/1994','Nữ','Đồng Nai','0987123942')

INSERT INTO EMPLOYEE
VALUES('Lê Thị Thanh Trúc','06/25/1985','Nữ','Cà Mau','0349235013')
GO

INSERT INTO EMPLOYEE
VALUES('Mai Anh Kiệt','11/07/1996','Nam','Hồ Chí Minh','0830478264')
GO

INSERT INTO EMPLOYEE
VALUES('Trần Tuấn Anh','09/12/1990','Nam','Đồng Nai','0976204584')
GO

INSERT INTO EMPLOYEE
VALUES('Nguyễn Trần Anh Nguyên','07/30/1987','Nam','Tây Ninh','0946327821')
GO

INSERT INTO EMPLOYEE
VALUES('Nguyễn Thị Minh Thư','02/16/1988','Nữ','Tiền Giang','0917823642')
GO

INSERT INTO EMPLOYEE
VALUES('Trần Huỳnh Mai Trang','01/10/1989','Nữ','Long An','0923478206')
GO

INSERT INTO EMPLOYEE
VALUES('Nguyễn Thị Anh Thư','01/10/1989','Nữ','Long An','0123895860')
GO


select * from DEPARTMENT

INSERT INTO DEPARTMENT
VALUES('Phòng nhân sự',3)

INSERT INTO DEPARTMENT
VALUES('Phòng IT',9)

INSERT INTO DEPARTMENT
VALUES('Phòng Sales',15)

select * from ACCOUNT

INSERT INTO ACCOUNT
VALUES('admin','admin1234')
GO

INSERT INTO ACCOUNT
VALUES('huongttq','huong1987')
GO

INSERT INTO ACCOUNT
VALUES('trucltt','truc1985')
GO

INSERT INTO ACCOUNT
VALUES('minhhtp','minh1997')
GO

INSERT INTO ACCOUNT
VALUES('annv','an1990')
GO

INSERT INTO ACCOUNT
VALUES('hungtt','hung1993')
GO

INSERT INTO ACCOUNT
VALUES('nhanlt','nhan1994')
GO

INSERT INTO ACCOUNT
VALUES('kietma','kiet1996')
GO

INSERT INTO ACCOUNT
VALUES('anhtt','anh1990')
GO

INSERT INTO ACCOUNT
VALUES('nguyennta','nguyen1987')
GO

INSERT INTO ACCOUNT
VALUES('thuntm','thu1988')
GO

select * from WORK_ON


INSERT INTO WORK_ON
VALUES(1,2,'Part-time')
GO 

INSERT INTO WORK_ON
VALUES(2,2,'Employee')
GO 

INSERT INTO WORK_ON
VALUES(3,3,'Manager')
GO 

INSERT INTO WORK_ON
VALUES(4,3,'Employee')
GO 

INSERT INTO WORK_ON
VALUES(5,1,'Employee')
GO 

INSERT INTO WORK_ON
VALUES(6,1,'Manager')
GO 

INSERT INTO WORK_ON
VALUES(7,2,'Part-time')

INSERT INTO WORK_ON
VALUES(8,2,'Employee')


INSERT INTO WORK_ON
VALUES(9,2,'Employee')
GO 

INSERT INTO WORK_ON
VALUES(10,3,'Employee')
GO 

INSERT INTO WORK_ON
VALUES(11,2,'Manager')
GO 

INSERT INTO WORK_ON
VALUES(3,1,'Employee')
GO

INSERT INTO WORK_ON
VALUES(6,3,'Employee')
GO

INSERT INTO WORK_ON
VALUES(11,3,'Employee')
GO

INSERT INTO WORK_ON
VALUES(1,3,'test')
GO

INSERT INTO WORK_ON
VALUES(1,1,'SUIGHE')
GO

select * from SALARY
SELECT * FROM EMPLOYEE
SELECT * FROM WORK_ON
select * from DEPARTMENT
select * from ACCOUNT

INSERT INTO SALARY
VALUES (1,4000000,1,0)
GO

INSERT INTO SALARY
VALUES (2,9850000,0,500000)
GO

INSERT INTO SALARY
VALUES (3,15000000,0,0)
GO

INSERT INTO SALARY
VALUES (4,8350000,2,3500000)
GO

INSERT INTO SALARY
VALUES (5,8000000,0,0)
GO

INSERT INTO SALARY
VALUES (6,15000000,0,1500000)
GO

INSERT INTO SALARY
VALUES (7,4000000,0,0)
GO

INSERT INTO SALARY
VALUES (8,7320000,1,250000)
GO

INSERT INTO SALARY
VALUES (9,8470000,0,0)
GO

INSERT INTO SALARY
VALUES (10,8350000,0,500000)
GO

INSERT INTO SALARY
VALUES (11,14700000,0,2000000)
GO

Update WORK_ON
Set DeptId = 2
Where EmpId=1

Select e.EmpName, w.DeptId, w.Position
from WORK_ON as w, EMPLOYEE as e
Where e.EmpId = w.EmpId

